---
image: quay.io/elastx/ci-terraform:master

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PUBLIC_KEY" >~/.ssh/id.pub
  - chmod 0644 ~/.ssh/id.pub
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - echo "StrictHostKeyChecking no" > ~/.ssh/config

stages:
  - version
  - plan
  - build_all
  - destroy_all

version:
  stage: version
  script:
    - terraform version
  when: manual

terraform_plan:
  stage: plan
  allow_failure: true
  script:
    - cd 01_Router_Networking_Bastion
    - terraform init -var-file example.auto.tfvars
    - terraform plan -var-file example.auto.tfvars
    - cd ../02_Web_Servers_LBaaS
    - terraform init -var-file example.auto.tfvars
    - terraform plan -var-file example.auto.tfvars
  when: manual

build_all:
  stage: build_all
  allow_failure: true
  script:
    - cd 01_Router_Networking_Bastion
    - terraform init -var-file example.auto.tfvars
    - terraform apply -var-file example.auto.tfvars -auto-approve
    - cd ../02_Web_Servers_LBaaS
    - terraform init -var-file example.auto.tfvars
    - terraform apply -var-file example.auto.tfvars -auto-approve

destroy_all:
  stage: destroy_all
  script:
    - cd 01_Router_Networking_Bastion
    - terraform init -var-file example.auto.tfvars
    - terraform destroy -var-file example.auto.tfvars -auto-approve
    - cd ../02_Web_Servers_LBaaS
    - terraform init -var-file example.auto.tfvars
    - terraform destroy -var-file example.auto.tfvars -auto-approve

