---
image: quay.io/elastx/ci-terraform:master

stages:
  - version
  - plan
  - build_all
  - destroy_all

version:
  stage: version
  script:
    - terraform version
  when: manual

terraform_plan:
  stage: plan
  allow_failure: true
  script:
    - cd 01_Router_Networking_Bastion
    - terraform init -var-file example.auto.tfvars
    - terraform plan -var-file example.auto.tfvars
  when: manual

build_all:
  stage: build_all
  allow_failure: true
  script:
    - cd 01_Router_Networking_Bastion
    - terraform init -var-file example.auto.tfvars
    - terraform apply -var-file example.auto.tfvars -auto-approve

destroy_all:
  stage: destroy_all
  script:
    - cd 01_Router_Networking_Bastion
    - echo $HOME
    - terraform init -var-file example.auto.tfvars
    - terraform destroy -var-file example.auto.tfvars -auto-approve
